/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGrokRouteImport } from './routes/api/grok'
import { Route as ApiLlmRouteImport } from './routes/api/llm'
import { Route as ApiNaiRouteImport } from './routes/api/nai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrokRoute = ApiGrokRouteImport.update({
  id: '/api/grok',
  path: '/api/grok',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmRoute = ApiLlmRouteImport.update({
  id: '/api/llm',
  path: '/api/llm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNaiRoute = ApiNaiRouteImport.update({
  id: '/api/nai',
  path: '/api/nai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/grok': typeof ApiGrokRoute
  '/api/llm': typeof ApiLlmRoute
  '/api/nai': typeof ApiNaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/grok': typeof ApiGrokRoute
  '/api/llm': typeof ApiLlmRoute
  '/api/nai': typeof ApiNaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/grok': typeof ApiGrokRoute
  '/api/llm': typeof ApiLlmRoute
  '/api/nai': typeof ApiNaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/grok' | '/api/llm' | '/api/nai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/grok' | '/api/llm' | '/api/nai'
  id: '__root__' | '/' | '/api/grok' | '/api/llm' | '/api/nai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGrokRoute: typeof ApiGrokRoute
  ApiLlmRoute: typeof ApiLlmRoute
  ApiNaiRoute: typeof ApiNaiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grok': {
      id: '/api/grok'
      path: '/api/grok'
      fullPath: '/api/grok'
      preLoaderRoute: typeof ApiGrokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm': {
      id: '/api/llm'
      path: '/api/llm'
      fullPath: '/api/llm'
      preLoaderRoute: typeof ApiLlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nai': {
      id: '/api/nai'
      path: '/api/nai'
      fullPath: '/api/nai'
      preLoaderRoute: typeof ApiNaiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGrokRoute: ApiGrokRoute,
  ApiLlmRoute: ApiLlmRoute,
  ApiNaiRoute: ApiNaiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
